apiVersion: v1
kind: ConfigMap
metadata:
  name: confluence-config
  namespace: confluence
  labels:
    app.kubernetes.io/name: confluence
    app.kubernetes.io/component: atlassian
data:
  JVM_MINIMUM_MEMORY: 512m
  JVM_MAXIMUM_MEMORY: 1024m
  SET_PERMISSIONS: "true"
  ATL_JDBC_URL: jdbc:postgresql://database-1.cgwa6romgzct.us-east-2.rds.amazonaws.com:5432/confluence
  ATL_JDBC_USER: postgres
  ATL_DB_TYPE: postgresql
  ATL_DB_POOLMINSIZE: "20"
  ATL_DB_POOLMAXSIZE: "100"
  ATL_DB_TIMEOUT: "60"
  ATL_DB_IDLETESTPERIOD: "100"
  ATL_DB_VALIDATE: "false"
  ATL_DB_ACQUIREINCREMENT: "1"