apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: confluence
  name: confluence-db-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.31.8.193
    path: {{nfspath}}