apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-deployment
  namespace: confluence
  labels:
    app.kubernetes.io/service: confluence
    app.kubernetes.io/app: confluence

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: confluence
  template:
    metadata:
      labels:
        app.kubernetes.io/app: confluence
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: confluence
          image: atlassian/confluence-server:7.4.4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              port: 8090
              path: /status
            initialDelaySeconds: 180
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          envFrom:
          - configMapRef:
              name: confluence-config
          env:
           - name: ATL_JDBC_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: confluencedb-password
                 key: dbpassword
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/confluence"
            name: confluence-p-volume
      volumes:
      - name: confluence-p-volume
        persistentVolumeClaim:
          claimName: confluence-pvc