apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  namespace: confluence
  labels:
    app.kubernetes.io/app: confluence
spec:
  type: LoadBalancer
#  externalIPs:
#    - 10.1.1.24
#    - 10.1.1.25
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    app.kubernetes.io/app: confluence